// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using csharp_practice.EFTest;

namespace csharp_practice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("csharp_practice.EFTest.SysConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConfigKey");

                    b.Property<string>("ConfigSection");

                    b.Property<string>("ConfigValue");

                    b.Property<DateTime>("GmtCreate");

                    b.HasKey("Id");

                    b.ToTable("SysConfigs");
                });

            modelBuilder.Entity("csharp_practice.EFTest.SysResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("GmtCreate");

                    b.Property<string>("ResName");

                    b.HasKey("Id");

                    b.ToTable("SysResources");
                });

            modelBuilder.Entity("csharp_practice.EFTest.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("GmtCreate");

                    b.Property<string>("RoleName");

                    b.HasKey("Id");

                    b.ToTable("SysRoles");
                });

            modelBuilder.Entity("csharp_practice.EFTest.SysUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account");

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<DateTime>("GmtCreate");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("SysUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
